# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-back-end:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: pwd
      - run: cd back-end # navigate into the express app directory
      - run: npm install # install all dependencies listed in package.json
  test-back-end:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: pwd
      - run: cd back-end # navigate into the express app directory
      - run: npm install # install all dependencies listed in package.json
      - run: npm test # run all unit tests

# Orchestrate our job run sequence
workflows:
  build-and-test-express:
    jobs:
      - build-back-end
      - test-back-end
